### ISSUE TITLE
Issue converting my bep2 rune on trust wallet

### ISSUE THREAD

**Issue by Dymnd2** [bnb-chain/bcfusion#10]
I have issues converting my (175) bep2 rune to thorchain.. 
pls help me out

**Comment by ddaraji** [comment]
I'm also facing same problem, did you get any solution? If yes, then could you please help me in this. Telegram - @dhax007

**Comment by STdevK** [comment]
Please reach out to ThorChain team for assistance.
https://explorer.bnbchain.org/asset/RUNE-B1A

**Comment by DevFix0512** [comment]
Hello @ddaraji A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by bilalkhanswatim** [comment]
HBl
