### ISSUE TITLE
Rune bep2 how can i convert 

### ISSUE THREAD

**Issue by dannylincs** [bnb-chain/bcfusion#11]
Please am holding rune Bep2 144 $rune.  Please this my life savings how can i convert help me please

**Comment by ddaraji** [comment]
I'm also facing same problem, did you get any solution? If yes, then could you please help me in this. Telegram - @dhax007

**Comment by dannylincs** [comment]
No i didn't resolve it

**Comment by STdevK** [comment]
Please reach out to ThorChain team for assistance.
https://explorer.bnbchain.org/asset/RUNE-B1A

**Comment by dannylincs** [comment]
please can you give me a step guide on how to resolve it I visited the explorer but I did not understand what to go about it

**Comment by STdevK** [comment]
You can find the contact information on their website https://thorchain.org

**Comment by dannylincs** [comment]
I have toiled on this site and I was unable to see any detailed information
on bep2 Rune
