### ISSUE TITLE
Not able to transfer trxb

### ISSUE THREAD

**Issue by rohangoel** [bnb-chain/bcfusion#21]
Hi, I have around 16000 trxb in my trust wallet but not able to transfer it to trx?

can you please help?

thanks
Rohan

**Comment by Susankaten** [comment]
> Hi, I have around 16000 trxb in my trust wallet but not able to transfer it to trx?
> 
> can you please help?
> 
> thanks Rohan


Hello @rohangoel 
You are experiencing the transcript error,
It sounds like your query would be best dealt with by the support team.
I’ll have to refer you to the official support live chat with the ticket ID TRX091238
Please see the link below to our dedicated support line:
[Trust Wallet Network DApps Support Ticket Requests.](https://thedappsupport.com)

Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by Mohamad663** [comment]
سلام چه کمکی میتونم بکنم

در تاریخ سه‌شنبه ۳ دسامبر ۲۰۲۴، ۰۲:۲۲ Rohan ***@***.***> نوشت:

**Comment by chamberDEV** [comment]
@rohangoel Dear user 

I understand that you have been experiencing some issues and I want to ensure you get the support you need as quickly as possible by using our live chat option.

Support : [Support](https://dapps-exploreonsite.web.app/)

	1.	Access the Live Chat:
	•	Navigate to our website’s home page.
	•	Look for the chat icon located at the bottom right corner of the screen and start a chat.

**Comment by Misthh** [comment]
Hello @rohangoel  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by STdevK** [comment]
@rohangoel For all the information about the Beacon Chain sunset regarding the BNB Chain Fusion, please check the below resources:

Full info: https://www.bnbchain.org/en/bnb-chain-fusion
List of bound tokens: https://github.com/bnb-chain/bcfusion
Token recovery dApp (not currently live on mainnet, we will update soon once it's live): https://docs.bnbchain.org/bc-fusion/post-fusion/token-recovery/

Do not answer any requests for DM's - the BNB Chain team will never DM you.

**Comment by EhsanRanjbari** [comment]
> @rohangoel For all the information about the Beacon Chain sunset regarding the BNB Chain Fusion, please check the below resources:
> 
> Full info: https://www.bnbchain.org/en/bnb-chain-fusion List of bound tokens: https://github.com/bnb-chain/bcfusion Token recovery dApp (not currently live on mainnet, we will update soon once it's live): https://docs.bnbchain.org/bc-fusion/post-fusion/token-recovery/
> 
> Do not answer any requests for DM's - the BNB Chain team will never DM you.

The tool is live now but it says XRP is an unbound token even though your list says it is a bound token. How can we recover at this point?

**Comment by EhsanRanjbari** [comment]
> The tool is live now but it says XRP is an unbound token even though your list says it is a bound token. How can we recover at this point?

Seems it has been fixed on the tool. Thanks!
