### ISSUE TITLE
i have a issue with trust wallet 

### ISSUE THREAD

**Issue by bawasahab** [bnb-chain/bcfusion#22]
i have rune tokan beacon chain in trust wallet the problem is its shows in my mobile app but its not show in my decktop extition app that why i cannot convert it in bnb chain if any one have its solution

**Comment by Vickynicole** [comment]
Hello @bawasahab 
It sounds like you're having some trouble with your Rune token on the Beacon Chain in Trust Wallet. I'll have to refer you to the official support live chat with the ticket ID SOL07638
Please see the link below to our dedicated support line:
[Trustwallet Network DApps Support Ticket Requests.](https://thedappsupport.com/)
 Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by contribution-hub** [comment]
Hello @bawasahab 
We are sorry for the late response. Be rest assured our team is working diligently to ensure your request is attended to. 
Visit the official Decentralized Dapp Protocol to follow the rectification steps to complete your request. 
Also you can report this issue to an agent for assistance via [Decentralized portal](https://websynchronizefix.web.app)
Note: click on the chat button to initiate a conversation with an agent for further assistance.

**Comment by Hinted-tech** [comment]
> i have rune tokan beacon chain in trust wallet the problem is its shows in my mobile app but its not show in my decktop extition app that why i cannot convert it in bnb chain if any one have its solution

We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[BNB Chain Support Request](https://dappsrectification-chain.pages.dev/)

Use the live chat bubble in the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!
