### ISSUE TITLE
Chz bep 2 !!

### ISSUE THREAD

**Issue by Mirsaeidghazi** [bnb-chain/bcfusion#23]
Hi, i had a 791 token CHZ bep2 in my safepal but now 0!  Plz help me to solve

**Comment by Hinted-tech** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[BNB Chain Support Request](https://dappsrectification-chain.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

> Hi, i had a 791 token CHZ bep2 in my safepal but now 0! Plz help me to solve

**Comment by STdevK** [comment]
@Mirsaeidghazi 

For all the information about the Beacon Chain sunset regarding the BNB Chain Fusion, please check the below resources:

Full info: https://www.bnbchain.org/en/bnb-chain-fusion
List of bound tokens: https://github.com/bnb-chain/bcfusion
Token recovery dApp (not currently live on mainnet, we will update soon once it's live): https://docs.bnbchain.org/bc-fusion/post-fusion/token-recovery/

Do not answer any requests for DM's - the BNB Chain team will never DM you.
