### ISSUE TITLE
XRP Uable to recover!

### ISSUE THREAD

**Issue by EhsanRanjbari** [bnb-chain/bcfusion#24]
Hi. I am trying to recover XRP using token recovery tool but it says it is an `unbound token`. I checked the list [here](https://github.com/bnb-chain/bcfusion) and the XRP token is listed which means I should able to recover it. Can someone clarify this?

**Comment by LiveSupport-debug** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/)

Ticket ID: WL240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation

**Comment by EhsanRanjbari** [comment]
Seems it has been fixed on the tool. Thanks!
Closing as completed!

**Comment by Jarrel-doe** [comment]
Hello @EhsanRanjbari  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)
