### ISSUE TITLE
XRP

### ISSUE THREAD

**Issue by StevieSimple** [bnb-chain/bcfusion#8]
XRP XLM XDC SETTLE ON DEMAND! 50K+ other tokens do NOT. What will that be worth? 
XLM IS THE GEM? 
XLM is Flying under the radar n seems to be less value BUTT what ever happens to XRP WILL HAPPEN TO XLM!

**Comment by Julietnacy** [comment]
@StevieSimple XLM could definitely be a gem! It's flying under the radar but who knows, what happens to XRP might happen to XLM too! Keep an eye on those movements.
